### ISSUE TITLE
Cannot install / improve installation section in README

### ISSUE THREAD

**Issue by NavidSassan** [firecat53/bitwarden-menu#15]
Seems like a cool project, however none of the provided installation options work for me. What i tried:
```bash
$ python3 -m venv --system-site-packages venv
$ source venv/bin/activate
$ pip install -U pip wheel
Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (22.0.3)
Requirement already satisfied: wheel in ./venv/lib/python3.10/site-packages (0.37.1)

$ pip install bitwarden-menu
ERROR: Could not find a version that satisfies the requirement bitwarden-menu (from versions: none)
ERROR: No matching distribution found for bitwarden-menu
```

The Archlinux AUR link returns a 404.

And the README is not clear on how to run it after cloning the git repository.

I would like to try out the program, can you please help me?

**Comment by firecat53** [comment]
Ah, so sorry! I haven't completed some enhancements to the project yet that I
want to before uploading to Pypi, so the instructions as written don't work!
There's also no Archlinux package yet. I started the repo as a copy of my
[Keepmenu](https://github.com/firecat53/keepmenu) project and have been slowly
updating pieces as I find time to work on it. I'm using bitwarden-menu daily on
my laptop though and it's been super convenient and very fast to lookup and type
entries!

1. Download the project and change to that directory
2. `python -m venv venv`
3. `source venv/bin/activate`
4. `pip install -U .`
5. `bwm` (bwm is the name of the executable)

I'd also recommend looking into the [pipx](https://pypa.github.io/pipx/) project
for installing CLI apps into virtualenvs.

Thanks for your interest! Happy to help more. Maybe I'll spend some of my
vacation time here polishing this up some more and releasing to the world :)

**Comment by firecat53** [comment]
I've released bitwarden-menu on Pypi and the AUR, fyi. Let me know if you have
any other issues. Thanks for your interest!

**Comment by NavidSassan** [comment]
Hi, sorry for the delay, and many thanks for your feedback :) Will try it out when I have some more time.
