### ISSUE TITLE
Feature request: Add lock argument

### ISSUE THREAD

**Issue by electrickite** [firecat53/bitwarden-menu#21]
It would be great to have the option to lock the vault from the bwm command. This can be accomplished right now by running:

    $ killall bwm; rm -f ~/.cache/.bwm-auth

but this feels a little clunky.

**Comment by electrickite** [comment]
Just to expand this a bit, another way to accomplish this is to run:

    $ killall bwm; bw lock

**Comment by firecat53** [comment]
So you want to lock it from the command line without opening bwm? Because the 'Lock Vault' option is available and that locks the vault as well as removing the .bwm-auth file. Seems like `<keystroke to open bwm>k` gets you the same result faster than typing `bwm --lock` would. Just sayin' :P

**Comment by electrickite** [comment]
My use case for the lock command line option is locking the vault when the session locks or the computer sleeps. Session lock calls a script which then locks bwm among other things.

So, not so much for direct use at the command line, but in scripting.
