### ISSUE TITLE
Autotype Option Doesn't Override autotype Sequence in config.ini 

### ISSUE THREAD

**Issue by uxdiin** [firecat53/bitwarden-menu#27]
## Expected
bwm override autotype sequence

## Actual Result
bwm just outputs inputed string

**Comment by firecat53** [comment]
Sorry for the delayed response!

I'm not seeing the same behavior. In my config.ini I have `autotype_default = {USERNAME}{TAB}{PASSWORD}{ENTER}`.
When I run `bwm -a '{PASSWORD}'`, the password entry is typed out for the selected entry. This works for other fields such as `{USERNAME}`  or `{URL}`. 

Can you provide any other information?

**Comment by uxdiin** [comment]
Hello, idk what I have done, but I don't have that issue anymore. I think I will close this issue.
