### ISSUE TITLE
pynput not work in nixos

### ISSUE THREAD

**Issue by hmanhng** [firecat53/bitwarden-menu#29]
It seems pynput doesn't work on nixos
And can you help with dotool?

**Comment by firecat53** [comment]
I'm going to need a little more information from you. 

1. Are you using Wayland (e.g. sway) or X (e.g. i3) ? Pynput doesn't work on Wayland.
2. Dotool isn't setup yet to work with bitwarden-menu. Keepmenu has support already and it's on my todo list.

**Comment by hmanhng** [comment]
1. I use wayland and didn't know pynput didn't work on it.
2. I have a problem with bwm, it cannot autotype(with ydotool) or copy TOTP and I have no way to get them.

**Comment by hmanhng** [comment]
I think autotype and copy TOTP to clipboard are good
 I use Nixos vs wm Hyprland
Can you check again?

**Comment by firecat53** [comment]
I'm sorry, I'm not understanding what you want me to check? Did you get autotype and copy to clipboard working?

**Comment by hmanhng** [comment]
> I'm sorry, I'm not understanding what you want me to check? Did you get autotype and copy to clipboard working?

I can't get TOTP, neither autotype nor copy to clipboard
 i use nix + hyprland

**Comment by firecat53** [comment]
Ok, have you followed the installation and configuration guides in the docs? Post your bwm config.ini. Any error messages?

**Comment by uxdiin** [comment]
> > I'm sorry, I'm not understanding what you want me to check? Did you get autotype and copy to clipboard working?
> 
> I can't get TOTP, neither autotype nor copy to clipboard i use nix + hyprland

have you solve your problem? I am facing the same issue. My config in X but not on wayland

**Comment by firecat53** [comment]
Closing. Please reopen if you have any additional information. Thanks!
