### ISSUE TITLE
Incorrect entery on non english keyboard layouts

### ISSUE THREAD

**Issue by jonwin1** [firecat53/bitwarden-menu#34]
When using a non english keyboard layout things are sometimes incorrectely typed, for example with a swedish keyboard layout @ is entered as " and $ is entered as ¤. I would guess this is because some symbols are placed differently on a swedish keyboard e.g. shift + 2 is @ on english keyboards and " on swedish.

**Comment by firecat53** [comment]
Take a look through firecat53/keepmenu#155 and see if any of the suggestions there (using xdotool, etc.) help sort out the issue. If you can't sort it, my only suggestion is to use `password_chars` and `password_char_presets` to specifically assign allowed keys that are correctly typed for you. It's not ideal...

**Comment by jonwin1** [comment]
Thank you, but unfortunately I were not able to get that to work. Instead I set my default layout to us and bound capslock to toggle to se layout, like this:

    $ setxkbmap -query
    ...
    layout:     us,se
    options:    grp:caps_toggle,grp_led:caps

This way bwm uses the deafault layout and I can use a swedish layout, not the cleanest solution but it works.

**Comment by firecat53** [comment]
I'm glad you found a workaround at least! It's been a challenge for both of these projects finding a combination of launcher and 'typer' (xdotool, ydotool, wtype, etc) that works for all keyboard layouts and special characters.

Are you currently using xdotool or pynput? If you ever switch to Wayland, please update me on if or what you able to get working for you.

I'll leave this open for now.

**Comment by jonwin1** [comment]
I was actually able to get it to work after some further tinkering. I use NixOS and even though my layout is set to `se` in my config I need to run `setxkbmap se` to get xdotool to work correctly. So by adding `displayManager.sessionCommands = "setxkbmap se";` in my config I could get bwm to work using xdotool.

**Comment by firecat53** [comment]
Great, glad you got it working! Looks like that's documented in docs/configure.md but I can see why NixOS would make that not as clear.

If you do end up getting it working on Wayland at some point, please let me know. Thanks! I'll close this for now. Re-open if necessary.
